[project]
name = "python-package-firewall"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "beautifulsoup4>=4.14.2",
    "fastapi==0.122.0",
    "httpx>=0.28.1",
    "license-expression==30.4.4",
    "pydantic-settings>=2.12.0",
    "pytest>=9.0.1",
    "python-dotenv>=1.2.1",
    "rapidfuzz==3.14.3",
    "requests==2.32.5",
    "spdx-license-list==3.27.0",
    "uvicorn==0.38.0",
]

[tool.pytest.ini_options]
markers = [
    "slow: marks tests as slow (deselect with '-m \"not slow\"')",
]
